### ISSUE TITLE
Dockmentation needed

### ISSUE THREAD

**Issue by MallikarjunHt** [MallikarjunHt/Training#3]
i have multiple projects that i built while learning. 
Dockmentation is needed for this repo, each folder create a readme and add discription for each project.

feel free to raise an issue and lets build the document together.

**Comment by Abhicoder03** [comment]
Hey, I can work on this. Could you tell me what exactly we need to do?

**Comment by MallikarjunHt** [comment]
Individual folders there are no readme files and i need to document each folder explaining the **code** Or **Installatin procisure** and a consolidated document explaining each foldure.
